# Generated by Django 4.0.3 on 2022-03-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uploaded_keywords',
            field=models.ManyToManyField(related_name='uploaded_by', through='keywords.KeywordUploadProfile', to='keywords.keywordresult'),
        ),
    ]
