# Generated by Django 4.0.3 on 2022-03-30 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('total_results', models.PositiveBigIntegerField()),
                ('total_links', models.IntegerField()),
                ('total_adwords', models.IntegerField()),
                ('html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KeywordUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'In-Progress'), (2, 'Completed')], db_index=True, default=1, verbose_name='Status')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordUploadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('KeywordResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.keywordresult')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.keywordupload')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='keywordresult',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('keyword'), name='unique_upper_keyword_name'),
        ),
    ]
